spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      # 以下の設定とbanner.gifファイルを配置すれば設定される
  # banner:
    # image:
      # bitdepth: 8
      # pixelmode: block
