spring:
  datasource:
    first:
      jdbcUrl: jdbc:postgresql://localhost:5432/postgres
      username: postgres
      password: password
      driverClassName: org.postgresql.Driver
    second:
      jdbcUrl: jdbc:postgresql://localhost:5433/postgres
      username: postgres
      password: password
      driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
