service: test

provider:
  name: aws
  runtime: java11
  timeout: 30

  region: ap-northeast-1

package:
  artifact: target/mavenlambda-0.0.1-SNAPSHOT-aws.jar

functions:
  hello:
    handler: org.springframework.cloud.function.adapter.aws.SpringBootStreamHandler
    events:
      - http:
          path: testapi
          method: get
          integration: lambda-proxy
          request:
            template:
              application/json: '$input.json("$")'
